### create user
POST expressjs-development-c804.up.railway.app/api/v1/auth/register
Content-Type: application/json

{
    "first_name": "Bagus Dwi",
    "last_name": "Putra Adiyono",
    "email": "sugab.dwi88@gmail.com",
    "password": "123456"
}

### Login User
POST expressjs-development-c804.up.railway.app/api/v1/auth/login
Content-Type: application/json

{
    "email": "sugab.dwi88@gmail.com",
    "password": "123456"
}

### login token
GET expressjs-development-c804.up.railway.app/api/v1/auth/authenticate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RfbmFtZSI6IkJhZ3VzIER3aSIsImxhc3RfbmFtZSI6IlB1dHJhIEFkaXlvbm8iLCJlbWFpbCI6InN1Z2FiLmR3aTg4QGdtYWlsLmNvbSIsImlhdCI6MTcxNDcyNjI4MX0.x7yFBTNY58jpH11_X3yJEwcBasavyiTx0LELQWhzeIo

### Get all user
GET expressjs-development-c804.up.railway.app/api/v1/users

### Get all user by search
GET expressjs-development-c804.up.railway.app/api/v1/users?search=bagus

### Get user by id
GET expressjs-development-c804.up.railway.app/api/v1/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RfbmFtZSI6IkJhZ3VzIER3aSIsImxhc3RfbmFtZSI6IlB1dHJhIEFkaXlvbm8iLCJlbWFpbCI6InN1Z2FiLmR3aTg4QGdtYWlsLmNvbSIsImlhdCI6MTcxNDY1NjU0OX0.EDBoM0zj1CdbOaI2zRy7VkgjBC0xZd9C8ozzhjIW8lc

### Update profile
PUT expressjs-development-c804.up.railway.app/api/v1/users/1/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RfbmFtZSI6IkJhZ3VzIER3aSIsImxhc3RfbmFtZSI6IlB1dHJhIEFkaXlvbm8iLCJlbWFpbCI6InN1Z2FiLmR3aTg4QGdtYWlsLmNvbSIsImFkZHJlc3MiOm51bGwsIm9jY3VwYXRpb24iOm51bGwsImF2YXRhcl91cmwiOm51bGwsImlhdCI6MTcxNDQ4MDE1OX0.ieYowOwQnVRCwIiZdM5mgMxjH6dMRpVHQEo9MzURP0Y
Content-Type: application/json

{
    "address" : "Jl. Kebenaran",
    "occupation" : "IT Consultan" 
}

### Delete user
DELETE  expressjs-development-c804.up.railway.app/api/v1/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RfbmFtZSI6IkJhZ3VzIER3aSIsImxhc3RfbmFtZSI6IlB1dHJhIEFkaXlvbm8iLCJlbWFpbCI6InN1Z2FiLmR3aTg4QGdtYWlsLmNvbSIsImFkZHJlc3MiOm51bGwsIm9jY3VwYXRpb24iOm51bGwsImF2YXRhcl91cmwiOm51bGwsImlhdCI6MTcxNDQ4MDE1OX0.ieYowOwQnVRCwIiZdM5mgMxjH6dMRpVHQEo9MzURP0Y

### Get All Image
GET expressjs-development-c804.up.railway.app/api/v1/image
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RfbmFtZSI6IkJhZ3VzIER3aSIsImxhc3RfbmFtZSI6IlB1dHJhIEFkaXlvbm8iLCJlbWFpbCI6InN1Z2FiLmR3aTg4QGdtYWlsLmNvbSIsImFkZHJlc3MiOiJKbC4gVGlrdXMiLCJvY2N1cGF0aW9uIjoiSVQgQ29uc3VsdGFuIiwiYXZhdGFyX3VybCI6Imh0dHBzOi8vaWsuaW1hZ2VraXQuaW8vYmFndXNkcGEvMTcxNDQ4OTI3NTQzMl9YclpwdXpGbU0uanBnIiwiaWF0IjoxNzE0NDg5MjkyfQ.NziUVKMiz00jz7DK64S3HUiGoc58G3RuJlG8g-aK87A

### Get Image by ID
GET expressjs-development-c804.up.railway.app/api/v1/image/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RfbmFtZSI6IkJhZ3VzIER3aSIsImxhc3RfbmFtZSI6IlB1dHJhIEFkaXlvbm8iLCJlbWFpbCI6InN1Z2FiLmR3aTg4QGdtYWlsLmNvbSIsImFkZHJlc3MiOiJKbC4gVGlrdXMiLCJvY2N1cGF0aW9uIjoiSVQgQ29uc3VsdGFuIiwiYXZhdGFyX3VybCI6Imh0dHBzOi8vaWsuaW1hZ2VraXQuaW8vYmFndXNkcGEvMTcxNDQ4OTI3NTQzMl9YclpwdXpGbU0uanBnIiwiaWF0IjoxNzE0NDg5MjkyfQ.NziUVKMiz00jz7DK64S3HUiGoc58G3RuJlG8g-aK87A

### Put Image
PUT expressjs-development-c804.up.railway.app/api/v1/image/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RfbmFtZSI6IkJhZ3VzIER3aSIsImxhc3RfbmFtZSI6IlB1dHJhIEFkaXlvbm8iLCJlbWFpbCI6InN1Z2FiLmR3aTg4QGdtYWlsLmNvbSIsImFkZHJlc3MiOiJKbC4gVGlrdXMiLCJvY2N1cGF0aW9uIjoiSVQgQ29uc3VsdGFuIiwiYXZhdGFyX3VybCI6Imh0dHBzOi8vaWsuaW1hZ2VraXQuaW8vYmFndXNkcGEvMTcxNDQ4OTI3NTQzMl9YclpwdXpGbU0uanBnIiwiaWF0IjoxNzE0NDg5MjkyfQ.NziUVKMiz00jz7DK64S3HUiGoc58G3RuJlG8g-aK87A
Content-Type: application/json

{
    "title" : "Kalimat Booster",
    "description" : "Semangat!!!" 
}

### Delete Image by ID
DELETE expressjs-development-c804.up.railway.app/api/v1/image/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RfbmFtZSI6IkJhZ3VzIER3aSIsImxhc3RfbmFtZSI6IlB1dHJhIEFkaXlvbm8iLCJlbWFpbCI6InN1Z2FiLmR3aTg4QGdtYWlsLmNvbSIsImFkZHJlc3MiOiJKbC4gVGlrdXMiLCJvY2N1cGF0aW9uIjoiSVQgQ29uc3VsdGFuIiwiYXZhdGFyX3VybCI6Imh0dHBzOi8vaWsuaW1hZ2VraXQuaW8vYmFndXNkcGEvMTcxNDQ4OTI3NTQzMl9YclpwdXpGbU0uanBnIiwiaWF0IjoxNzE0NDg5MjkyfQ.NziUVKMiz00jz7DK64S3HUiGoc58G3RuJlG8g-aK87A